// frontend-react/src/components/packages/PackageCard.tsx
import { getPackageStatusLabel as getStatusLabel, getPackageStatusBg as getStatusBg, getPackageStatusText as getStatusText, getPaymentStatusLabel, getPaymentStatusTextClass } from '@/lib/package-status'
import { cn } from '@/lib/utils'
import { Card, CardContent } from '@/components/ui/card'
import { Package, Clock, Receipt, CheckCircle } from 'lucide-react'

interface PackageCardProps {
    pkg: any
    onViewPackage?: (id: number) => void
    onEditPackage?: (id: number) => void
    onDeletePackage?: (id: number) => void
    onDeliverPackage?: (id: number) => void
}

const formatDate = (dateString: string) => {
    if (!dateString) return 'N/A'
    const date = new Date(dateString)
    return date.toLocaleDateString('es-ES', {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    })
}

export default function PackageCard({
    pkg,
    onViewPackage,
    onEditPackage,
    onDeletePackage,
    onDeliverPackage
}: PackageCardProps) {
    return (
        <Card className="overflow-hidden hover:shadow-md transition-all duration-300 border-gray-200">
            <CardContent className="p-0">
                {/* Header Section */}
                <div
                    className="p-4 border-b border-gray-100 bg-gray-50/50 flex justify-between items-start cursor-pointer group"
                    onClick={() => onViewPackage?.(pkg.id)}
                >
                    <div className="flex items-center gap-3">
                        <div className="bg-indigo-100 p-2 rounded-lg text-indigo-600">
                            <Package size={20} />
                        </div>
                        <div>
                            <h3 className="font-semibold text-gray-900 group-hover:text-indigo-600 transition-colors">
                                #{pkg.tracking_number}
                            </h3>
                            <div className="flex items-center text-xs text-gray-500 mt-0.5 gap-1">
                                <Clock size={12} />
                                {formatDate(pkg.created_at)}
                            </div>
                        </div>
                    </div>
                    <span className={cn(
                        "px-2.5 py-1 text-[11px] font-semibold rounded-full border border-opacity-20 whitespace-nowrap",
                        getStatusBg(pkg.status),
                        getStatusText(pkg.status)
                    )}>
                        {getStatusLabel(pkg.status)}
                    </span>
                </div>

                {/* Content Section */}
                <div className="p-4 space-y-4">
                    {/* Route */}
                    {(pkg.origin_office_name || pkg.destination_office_name) && (
                        <div className="flex items-center gap-2 text-sm">
                            <span className="font-medium text-gray-900">{pkg.origin_office_name || 'Origen'}</span>
                            <svg className="w-4 h-4 text-gray-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                            </svg>
                            <span className="font-medium text-gray-900">{pkg.destination_office_name || 'Destino'}</span>
                        </div>
                    )}

                    {/* Routes / People */}
                    <div className="grid grid-cols-2 gap-4 text-sm">
                        <div>
                            <p className="text-xs text-gray-500 mb-1">Remitente</p>
                            <p className="font-medium text-gray-900 truncate">{pkg.sender_name || 'N/A'}</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-500 mb-1">Destinatario</p>
                            <p className="font-medium text-gray-900 truncate">{pkg.recipient_name || 'N/A'}</p>
                        </div>
                    </div>

                    {/* Products (Replacing Weight) */}
                    <div className="bg-gray-50 rounded-lg p-3 border border-gray-100">
                        <p className="text-xs text-gray-500 mb-1">Productos ({pkg.total_items_count || 0})</p>
                        <p className="text-sm text-gray-700 italic line-clamp-2">
                            {pkg.items && pkg.items.length > 0
                                ? pkg.items.map((item: any) => `${item.quantity}x ${item.description}`).join(', ')
                                : pkg.description || 'Sin descripción'}
                        </p>
                    </div>

                    {/* Footer / Payment */}
                    <div className="flex justify-between items-center pt-2">
                        <div className="flex items-center gap-1.5 text-sm">
                            <Receipt size={16} className="text-gray-400" />
                            <span className={cn("font-semibold text-xs", getPaymentStatusTextClass(pkg.payment_status))}>
                                {getPaymentStatusLabel(pkg.payment_status)}
                            </span>
                        </div>
                        <div className="text-right">
                            <p className="text-xs text-gray-500 leading-none">Total</p>
                            <p className="font-bold text-gray-900 leading-tight">Bs. {pkg.total_amount || '0.00'}</p>
                        </div>
                    </div>
                </div>

                {/* Actions */}
                <div className="px-4 py-3 bg-gray-50 border-t border-gray-100 flex items-center justify-end gap-2">
                    {pkg.status === 'arrived_at_destination' && (
                        <button
                            className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-md bg-indigo-600 text-white hover:bg-indigo-700 transition-colors shadow-sm"
                            onClick={() => onDeliverPackage?.(pkg.id)}
                        >
                            <CheckCircle size={14} className="mr-1.5" />
                            Entregar
                        </button>
                    )}
                    <button
                        className="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-md border border-gray-300 text-gray-700 bg-white hover:bg-gray-50 transition-colors"
                        onClick={() => onViewPackage?.(pkg.id)}
                    >
                        Ver
                    </button>
                    <button
                        className="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-md bg-gray-100 text-gray-700 hover:bg-gray-200 transition-colors"
                        onClick={() => onEditPackage?.(pkg.id)}
                    >
                        Editar
                    </button>
                    <button
                        className="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-md border border-red-200 text-red-600 bg-red-50 hover:bg-red-100 transition-colors"
                        onClick={() => onDeletePackage?.(pkg.id)}
                    >
                        Eliminar
                    </button>
                </div>
            </CardContent>
        </Card>
    )
}

// frontend/components/PackageCard.vue
<template>
  <div class="bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl transition-shadow duration-300 ease-in-out">
    <div class="p-5">
      <div class="flex justify-between items-start mb-3">
        <h3 class="text-lg font-semibold text-gray-800">Encomienda #{{ pkg.id }}</h3>
        <span :class="statusClass" class="px-3 py-1 text-xs font-semibold rounded-full">
          {{ statusText }}
        </span>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-2 text-sm text-gray-600 mb-4">
        <div>
          <strong class="font-medium text-gray-700">Remitente:</strong>
          <p>{{ pkg.sender_name || 'N/A' }}</p>
        </div>
        <div>
          <strong class="font-medium text-gray-700">Destinatario:</strong>
          <p>{{ pkg.recipient_name || 'N/A' }}</p>
        </div>
        <div class="col-span-1 md:col-span-2">
          <strong class="font-medium text-gray-700">Descripción:</strong>
          <p class="truncate">{{ pkg.description || 'Sin descripción' }}</p>
        </div>
        <div>
          <strong class="font-medium text-gray-700">Fecha Creación:</strong>
          <p>{{ formatDate(pkg.created_at) }}</p>
        </div>
         <div>
          <strong class="font-medium text-gray-700">Peso:</strong>
          <p>{{ pkg.total_weight ? `${pkg.total_weight} kg` : 'N/A' }}</p>
        </div>
        <div>
          <strong class="font-medium text-gray-700">Items:</strong>
          <p>{{ pkg.total_items_count || 0 }}</p>
        </div>
        <div>
          <strong class="font-medium text-gray-700">Monto Total:</strong>
          <p>Bs. {{ pkg.total_amount || '0.00' }}</p>
        </div>
      </div>

      <div class="mt-4 pt-4 border-t border-gray-200 flex flex-col sm:flex-row sm:justify-end sm:space-x-3 space-y-2 sm:space-y-0">
        <AppButton size="sm" variant="outline" @click="$emit('viewPackage', pkg.id)">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
          </svg>
          Ver
        </AppButton>
        <AppButton size="sm" variant="secondary" @click="$emit('editPackage', pkg.id)">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
          Editar
        </AppButton>
        <AppButton size="sm" variant="danger-outline" @click="$emit('deletePackage', pkg.id)">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
          </svg>
          Eliminar
        </AppButton>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import AppButton from '~/components/AppButton.vue';

const props = defineProps({
  pkg: {
    type: Object,
    required: true,
  },
});

defineEmits(['viewPackage', 'editPackage', 'deletePackage']);

const statusClass = computed(() => {
  const classes = {
    pending: 'bg-yellow-100 text-yellow-800',
    in_transit: 'bg-blue-100 text-blue-800',
    delivered: 'bg-green-100 text-green-800',
    cancelled: 'bg-red-100 text-red-800',
    // Add more statuses as needed
  };
  return classes[props.pkg.status] || 'bg-gray-100 text-gray-800';
});

const statusText = computed(() => {
  const texts = {
    pending: 'Pendiente',
    in_transit: 'En Tránsito',
    delivered: 'Entregado',
    cancelled: 'Cancelado',
    // Add more statuses as needed
  };
  return texts[props.pkg.status] || props.pkg.status || 'Desconocido';
});

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  const options = { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' };
  return new Date(dateString).toLocaleDateString('es-ES', options);
};

const formatCurrency = (amount) => {
  if (amount === null || amount === undefined) return 'N/A';
  return new Intl.NumberFormat('es-BO', { style: 'currency', currency: 'BOB' }).format(amount);
};

</script>

<style scoped>
/* Add any specific styles for the card if needed */
.truncate {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 250px; /* Adjust as needed */
}
</style>
