// frontend/src/components/dashboards/secretary/QuickActions.tsx
import { ClickableCard } from '@/components/ui/clickable-card'

interface QuickAction {
  id: string
  label: string
  description: string
  icon: React.ReactNode
  iconBg: string
  hoverBorder: string
  textHover: string
  onClick: () => void
}

export function QuickActions({ actions }: { actions: QuickAction[] }) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
      {actions.map((action) => (
        <ClickableCard
          key={action.id}
          ariaLabel={`${action.label}: ${action.description}`}
          onClick={action.onClick}
          className={`group p-4 lg:p-6 shadow-lg hover:shadow-xl duration-300 border-gray-200 ${action.hoverBorder} transform hover:-translate-y-1`}
        >
          <div className="flex items-center space-x-3 lg:space-x-4 px-4 lg:px-0">
            <div className={`flex items-center justify-center w-10 h-10 lg:w-12 lg:h-12 ${action.iconBg} rounded-xl transition-colors flex-shrink-0`}>
              {action.icon}
            </div>
            <div className="min-w-0 flex-1">
              <h3 className={`text-base lg:text-lg font-semibold text-gray-900 ${action.textHover} transition-colors truncate`}>
                {action.label}
              </h3>
              <p className="text-gray-600 text-sm truncate">{action.description}</p>
            </div>
          </div>
        </ClickableCard>
      ))}
    </div>
  )
}

export type { QuickAction }

// frontend/components/QuickActions.vue
<template>
  <div class="bg-white rounded-lg shadow">
    <div class="px-6 py-4 border-b border-gray-200">
      <h3 class="text-lg font-semibold text-gray-900">Acciones Rápidas</h3>
    </div>
    <div class="p-6 grid grid-cols-2 gap-4">
      <button 
        v-for="action in actions" 
        :key="action.label"
        class="flex flex-col items-center justify-center p-4 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
        @click="$emit('action-click', action.id)"
      >
        <component :is="action.icon" class="h-8 w-8 text-gray-500 mb-2" />
        <span class="text-sm font-medium text-gray-700">{{ action.label }}</span>
      </button>
    </div>
  </div>
</template>

<script setup>
defineProps({
  actions: {
    type: Array,
    required: true
  }
})

defineEmits(['action-click'])
</script>
