// frontend-react/src/components/layout/AdminHeader.tsx
import { useState, useRef, useEffect } from 'react'
import { Link, NavLink } from 'react-router'
import { useAuth } from '@/hooks/use-auth'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'

const NAV_LINKS: Record<string, { to: string; label: string }[]> = {
    admin: [
        { to: '/dashboards/dashboard-admin', label: 'Dashboard' },
        { to: '/admin/users', label: 'Usuarios' },
        { to: '/admin/buses', label: 'Buses' },
        { to: '/admin/routes', label: 'Rutas' },
    ],
    secretary: [
        { to: '/dashboards/dashboard-secretary', label: 'Dashboard' },
        { to: '/trips', label: 'Viajes' },
        { to: '/bookings', label: 'Boletos' },
        { to: '/packages', label: 'Encomiendas' },
        { to: '/clients', label: 'Clientes' },
    ],
}

function NavItem({ to, label, mobile }: { to: string; label: string; mobile?: boolean }) {
    const base = mobile
        ? 'block px-3 py-2 rounded-md text-base font-medium'
        : 'px-3 py-2 rounded-md text-sm font-medium'
    return (
        <NavLink
            to={to}
            className={({ isActive }) =>
                `${base} ${isActive ? 'text-indigo-600 bg-indigo-50' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50'}`
            }
        >
            {label}
        </NavLink>
    )
}

export default function AdminHeader() {
    const { user, userFullName, userInitials, userRole, logout } = useAuth()
    const [mobileOpen, setMobileOpen] = useState(false)
    const [userMenuOpen, setUserMenuOpen] = useState(false)
    const menuRef = useRef<HTMLDivElement>(null)
    const buttonRef = useRef<HTMLButtonElement>(null)

    const links = NAV_LINKS[userRole ?? ''] ?? []

    useEffect(() => {
        function handleClickOutside(e: MouseEvent) {
            if (
                menuRef.current &&
                !menuRef.current.contains(e.target as Node) &&
                buttonRef.current &&
                !buttonRef.current.contains(e.target as Node)
            ) {
                setUserMenuOpen(false)
            }
        }
        document.addEventListener('click', handleClickOutside)
        return () => document.removeEventListener('click', handleClickOutside)
    }, [])

    const handleLogout = async () => {
        setUserMenuOpen(false)
        setMobileOpen(false)
        await logout()
    }

    return (
        <header className="bg-white shadow-sm w-full relative z-40">
            <div className="w-full px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                    {/* Logo */}
                    <div className="flex items-center">
                        <Link to="/" className="text-xl font-bold text-gray-800">
                            Trans Comarapa
                        </Link>
                    </div>

                    {/* Desktop nav */}
                    <nav className="hidden md:flex space-x-4">
                        {links.map((link) => (
                            <NavItem key={link.to} {...link} />
                        ))}
                    </nav>

                    <div className="flex items-center">
                        {/* User menu */}
                        <div className="ml-3 relative">
                            <button
                                ref={buttonRef}
                                onClick={() => setUserMenuOpen((v) => !v)}
                                type="button"
                                className="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                id="user-menu-button"
                            >
                                <span className="sr-only">Open user menu</span>
                                <div className="h-8 w-8 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center text-white font-bold text-sm shadow-sm border border-white">
                                    {userInitials}
                                </div>
                            </button>

                            {userMenuOpen && (
                                <div
                                    ref={menuRef}
                                    className="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-50 animate-in fade-in zoom-in-95 duration-100"
                                    role="menu"
                                >
                                    <Link
                                        to="/profile"
                                        onClick={() => setUserMenuOpen(false)}
                                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                        role="menuitem"
                                    >
                                        Perfil
                                    </Link>
                                    <button
                                        onClick={handleLogout}
                                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                        role="menuitem"
                                    >
                                        Cerrar sesión
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Mobile menu button */}
                        <div className="-mr-2 flex md:hidden ml-2">
                            <button
                                type="button"
                                onClick={() => setMobileOpen((v) => !v)}
                                className="bg-white inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
                            >
                                <span className="sr-only">Open main menu</span>
                                {mobileOpen ? (
                                    <XMarkIcon className="block h-6 w-6" />
                                ) : (
                                    <Bars3Icon className="block h-6 w-6" />
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Mobile menu */}
            {mobileOpen && (
                <div className="md:hidden w-full bg-white border-t border-gray-100 shadow-inner">
                    <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                        {links.map((link) => (
                            <NavItem key={link.to} {...link} mobile />
                        ))}
                    </div>
                    <div className="pt-4 pb-3 border-t border-gray-200">
                        <div className="flex items-center px-5">
                            <div className="flex-shrink-0">
                                <div className="h-10 w-10 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center text-white font-bold text-lg shadow-sm border border-white">
                                    {userInitials}
                                </div>
                            </div>
                            <div className="ml-3">
                                <div className="text-base font-medium text-gray-800">{userFullName}</div>
                                <div className="text-sm font-medium text-gray-500">{user?.email ?? ''}</div>
                            </div>
                        </div>
                        <div className="mt-3 px-2 space-y-1">
                            <Link
                                to="/profile"
                                onClick={() => setMobileOpen(false)}
                                className="block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-900 hover:bg-gray-50"
                            >
                                Perfil
                            </Link>
                            <button
                                onClick={handleLogout}
                                className="block w-full text-left px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-900 hover:bg-gray-50"
                            >
                                Cerrar sesión
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </header>
    )
}

// frontend/components/layout/AdminHeader.vue
<template>
  <header class="bg-white shadow-sm w-full relative z-40">
    <div class="w-full px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <!-- Puedes reemplazar esto con un logo SVG o una imagen -->
            <NuxtLink to="/" class="text-xl font-bold text-gray-800">Trans Comarapa</NuxtLink>
          </div>
        </div>
        <nav class="hidden md:flex space-x-4">
          <ClientOnly>
            <!-- Admin Links -->
            <template v-if="authStore.userRole === 'admin'">
              <NuxtLink to="/dashboards/dashboard-admin" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Dashboard</NuxtLink>
              <NuxtLink to="/admin/users" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Usuarios</NuxtLink>
              <NuxtLink to="/admin/buses" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Buses</NuxtLink>
              <NuxtLink to="/admin/routes" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Rutas</NuxtLink>
            </template>
            
            <!-- Secretary Links -->
            <template v-if="authStore.userRole === 'secretary'">
              <NuxtLink to="/dashboards/dashboard-secretary" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Dashboard</NuxtLink>
              <NuxtLink to="/trips" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Viajes</NuxtLink>
              <NuxtLink to="/bookings" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Boletos</NuxtLink>
              <NuxtLink to="/packages" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Encomiendas</NuxtLink>
              <NuxtLink to="/clients" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Clientes</NuxtLink>
              <!-- <NuxtLink to="/reports/secretary" class="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium" active-class="text-indigo-600 bg-indigo-50">Reportes</NuxtLink> -->
            </template>
          </ClientOnly>
        </nav>
        <div class="flex items-center">
          <div class="ml-3 relative">
            <div>
              <button @click="isUserMenuOpen = !isUserMenuOpen" type="button" class="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <div v-if="userInfo?.profileImageUrl" class="h-8 w-8 rounded-full overflow-hidden">
                  <img class="h-full w-full object-cover" :src="userInfo.profileImageUrl" alt="User profile">
                </div>
                <div v-else class="h-8 w-8 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center text-white font-bold text-sm shadow-sm border border-white">
                  {{ userInitials }}
                </div>
              </button>
            </div>
            <transition
              enter-active-class="transition ease-out duration-100"
              enter-from-class="transform opacity-0 scale-95"
              enter-to-class="transform opacity-100 scale-100"
              leave-active-class="transition ease-in duration-75"
              leave-from-class="transform opacity-100 scale-100"
              leave-to-class="transform opacity-0 scale-95"
            >
              <div ref="userMenu" v-if="isUserMenuOpen" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-50" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                <NuxtLink to="/profile" @click="isUserMenuOpen = false" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem" tabindex="-1" id="user-menu-item-0">Perfil</NuxtLink>
                <a href="#" @click.prevent="handleLogout" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem" tabindex="-1" id="user-menu-item-1">Cerrar sesión</a>
              </div>
            </transition>
          </div>
        </div>
        <!-- Mobile menu button -->
        <div class="-mr-2 flex md:hidden">
            <button type="button" @click="mobileMenuOpen = !mobileMenuOpen" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg v-if="!mobileMenuOpen" class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" /></svg>
                <svg v-else class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <transition
      enter-active-class="transition-all duration-300 ease-out origin-top overflow-hidden"
      enter-from-class="transform scale-y-0 opacity-0 max-h-0"
      enter-to-class="transform scale-y-100 opacity-100 max-h-screen"
      leave-active-class="transition-all duration-200 ease-in origin-top overflow-hidden"
      leave-from-class="transform scale-y-100 opacity-100 max-h-screen"
      leave-to-class="transform scale-y-0 opacity-0 max-h-0"
    >
      <div v-if="mobileMenuOpen" class="md:hidden w-full bg-white border-t border-gray-100 shadow-inner" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
          <ClientOnly>
            <!-- Admin Links Mobile -->
            <template v-if="authStore.userRole === 'admin'">
              <NuxtLink to="/dashboards/dashboard-admin" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Dashboard</NuxtLink>
              <NuxtLink to="/admin/users" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Usuarios</NuxtLink>
              <NuxtLink to="/admin/buses" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Buses</NuxtLink>
              <NuxtLink to="/admin/routes" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Rutas</NuxtLink>
            </template>

            <!-- Secretary Links Mobile -->
            <template v-if="authStore.userRole === 'secretary'">
              <NuxtLink to="/dashboards/dashboard-secretary" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Dashboard</NuxtLink>
              <NuxtLink to="/trips" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Viajes</NuxtLink>
              <NuxtLink to="/bookings" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Boletos</NuxtLink>
              <NuxtLink to="/packages" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Encomiendas</NuxtLink>
              <NuxtLink to="/clients" class="text-gray-600 hover:bg-gray-50 hover:text-gray-900 block px-3 py-2 rounded-md text-base font-medium" active-class="text-indigo-600 bg-indigo-50">Clientes</NuxtLink>
            </template>
          </ClientOnly>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="flex items-center px-5">
                <div class="flex-shrink-0">
                    <div v-if="userInfo?.profileImageUrl" class="h-10 w-10 rounded-full overflow-hidden">
                      <img class="h-full w-full object-cover" :src="userInfo.profileImageUrl" alt="User profile">
                    </div>
                    <div v-else class="h-10 w-10 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 flex items-center justify-center text-white font-bold text-lg shadow-sm border border-white">
                      {{ userInitials }}
                    </div>
                </div>
                <div class="ml-3">
                    <div class="text-base font-medium text-gray-800">{{ userName }}</div>
                    <div class="text-sm font-medium text-gray-500">{{ userInfo?.email || 'usuario@example.com' }}</div>
                </div>
            </div>
            <div class="mt-3 px-2 space-y-1">
                <NuxtLink to="/profile" @click="mobileMenuOpen = false" class="block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-900 hover:bg-gray-50">Perfil</NuxtLink>
                <a href="#" @click="handleLogout" class="block px-3 py-2 rounded-md text-base font-medium text-gray-500 hover:text-gray-900 hover:bg-gray-50">Cerrar sesión</a>
            </div>
        </div>
        </div>
    </transition>
  </header>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useAuthStore } from '~/stores/auth'
import { useRouter } from 'vue-router'
import { usePersonData } from '~/composables/usePersonData'

const authStore = useAuthStore()
const router = useRouter()
const { getEffectiveName } = usePersonData()

const mobileMenuOpen = ref(false)
const isUserMenuOpen = ref(false)

const userInfo = computed(() => authStore.user)
const userName = computed(() => getEffectiveName(authStore.user))

const userInitials = computed(() => {
  if (authStore.user?.firstname && authStore.user?.lastname) {
    return `${authStore.user.firstname.charAt(0)}${authStore.user.lastname.charAt(0)}`.toUpperCase()
  }
  if (userName.value) {
    return userName.value.substring(0, 2).toUpperCase()
  }
  return 'U'
})

const handleLogout = async () => {
  await authStore.logout()
  isUserMenuOpen.value = false // Cierra el dropdown
  mobileMenuOpen.value = false // Cierra el menu mobil si estuviera abierto
  router.push('/') // Redirigir a la landing page
}

// Lógica para cerrar el dropdown si se hace clic fuera
const userMenu = ref(null) // Se necesitará una ref en el template para el div del dropdown

const handleClickOutside = (event) => {
  if (userMenu.value && !userMenu.value.contains(event.target)) {
    // Verifica también que no se haya hecho clic en el botón que abre el menú
    const userMenuButton = document.getElementById('user-menu-button');
    if (userMenuButton && !userMenuButton.contains(event.target)) {
        isUserMenuOpen.value = false
    }
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})

</script>

<style scoped>
/* Puedes agregar estilos específicos para el header aquí si es necesario */
</style>
