// frontend/src/components/trips/TripCardList.tsx
import { useNavigate } from 'react-router'
import { EmptyState } from '@/components/common'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { CalendarClock, Plus, Settings, User, Users } from 'lucide-react'
import { ROUTES } from '@/lib/routes'

interface SlotRoute {
    id: number
    origin: string
    destination: string
    price?: number
}

interface Slot {
    time: string
    trip: Record<string, unknown> | null
    route: SlotRoute
    schedule?: Record<string, unknown>
}

interface RouteGroup {
    route: SlotRoute
    slots: Slot[]
}

interface TripCardListProps {
    scheduleBoard: RouteGroup[]
    loading?: boolean
    selectedDate?: string
    onViewTrip?: (id: number) => void
    onCreateTrip?: (data: { routeId: number; date: string; time: string }) => void
    onSellTicket?: (tripId: number) => void
}

function getOccupancyInfo(trip: Record<string, unknown>) {
    const total = (trip.total_seats as number) ?? 0
    const available = (trip.available_seats as number) ?? 0
    const occupied = Math.max(0, total - available)
    const pct = total > 0 ? occupied / total : 0

    if (available === 0 && total > 0) return { occupied, total, label: 'Agotado', color: 'text-red-600' }
    if (pct >= 0.8) return { occupied, total, label: 'Lleno', color: 'text-red-500' }
    if (pct >= 0.5) return { occupied, total, label: 'Medio', color: 'text-yellow-600' }
    if (pct >= 0.25) return { occupied, total, label: 'Bajo', color: 'text-blue-600' }
    return { occupied, total, label: 'Disponible', color: 'text-green-600' }
}

function getDriverName(trip: Record<string, unknown>): string {
    const driver = trip.driver as { name?: string; firstname?: string; lastname?: string } | undefined
    if (!driver) return 'No asignado'
    if (driver.firstname) return `${driver.firstname} ${driver.lastname ?? ''}`.trim()
    if (driver.name) return driver.name
    return 'No asignado'
}

function getAssistantName(trip: Record<string, unknown>): string | null {
    const assistant = trip.assistant as { name?: string; firstname?: string; lastname?: string } | undefined
    if (!assistant) return null
    if (assistant.firstname) return `${assistant.firstname} ${assistant.lastname ?? ''}`.trim()
    if (assistant.name) return assistant.name
    return null
}

function getBusInfo(trip: Record<string, unknown>): { plate: string; floors: number } {
    const bus = trip.bus as { license_plate?: string; floors?: number } | undefined
    return {
        plate: bus?.license_plate || 'N/A',
        floors: bus?.floors ?? 1,
    }
}

function TripRow({
    slot,
    onViewTrip,
    onSellTicket,
    onCreateTrip,
    selectedDate,
    isPastDate,
    isSlotPast,
}: {
    slot: Slot
    onViewTrip?: (id: number) => void
    onSellTicket?: (tripId: number) => void
    onCreateTrip?: (data: { routeId: number; date: string; time: string }) => void
    selectedDate: string
    isPastDate: boolean
    isSlotPast: boolean
}) {
    const trip = slot.trip
    const isPast = isPastDate || isSlotPast
    const occ = trip ? getOccupancyInfo(trip) : { occupied: 0, total: 0, label: '--', color: 'text-muted-foreground/30' }
    const driverName = trip ? getDriverName(trip) : 'Sin viaje creado'
    const assistantName = trip ? getAssistantName(trip) : null
    const busInfo = trip ? getBusInfo(trip) : { plate: '--', floors: 0 }
    const tripId = trip ? (trip.id as number) : null
    const isSoldOut = trip ? occ.label === 'Agotado' : false
    const floorLabel = busInfo.floors >= 2 ? '2 Pisos' : busInfo.floors === 1 ? '1 Piso' : null

    const containerClasses = trip
        ? "border border-border rounded-lg px-3 sm:px-4 py-3 hover:shadow-md transition-shadow bg-card"
        : isPast
        ? "border border-dashed border-muted rounded-lg px-3 sm:px-4 py-3 bg-muted/20 opacity-60 cursor-not-allowed"
        : "border-2 border-dashed border-blue-200 rounded-lg px-3 sm:px-4 py-3 hover:border-blue-400 hover:bg-blue-50/30 transition-all cursor-pointer group"

    const timeClasses = trip
        ? "text-xl sm:text-2xl font-bold text-brand-navy"
        : "text-xl sm:text-2xl font-bold text-muted-foreground/30"

    const dividerClasses = trip ? "bg-border" : isPast ? "bg-muted" : "bg-blue-100"

    return (
        <div
            role="button"
            tabIndex={0}
            className={containerClasses}
            onClick={() => { if (!trip && !isPast) onCreateTrip?.({ routeId: slot.route.id, date: selectedDate, time: slot.time }) }}
            onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    if (!trip && !isPast) onCreateTrip?.({ routeId: slot.route.id, date: selectedDate, time: slot.time })
                }
            }}
        >
            {/* Top row: Content Alignment */}
            <div className="flex items-center gap-2 sm:gap-3 min-h-10">
                <span className={`flex-shrink-0 min-w-[3.5rem] sm:min-w-[5rem] ${timeClasses}`}>{slot.time}</span>

                <div className={`hidden sm:block h-8 w-px flex-shrink-0 ${dividerClasses}`} />

                <div className="flex-1 min-w-0 flex items-center justify-between gap-2 sm:gap-3">
                    {/* Bus Info */}
                    <div className="flex items-center gap-2 sm:gap-3 min-w-0">
                        <div className={`min-w-0 ${!trip ? "opacity-40" : ""}`}>
                            <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Bus No.</p>
                            <p className="text-sm font-bold text-foreground leading-tight truncate">{busInfo.plate}</p>
                        </div>
                        {floorLabel && (
                            <Badge variant="outline" className="hidden sm:inline-flex text-[10px] h-4 px-1.5 font-medium whitespace-nowrap">
                                {floorLabel}
                            </Badge>
                        )}
                    </div>

                    {/* Occupancy Info */}
                    <div className={`text-right min-w-0 ${!trip ? "opacity-30" : ""}`}>
                        <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Ocupación</p>
                        <p className="text-sm font-bold leading-tight whitespace-nowrap">
                            {trip ? (
                                <>
                                    <span className={occ.color}>{String(occ.occupied).padStart(2, '0')}/{occ.total}</span>
                                    <span className={`ml-1.5 text-[10px] uppercase ${occ.color} hidden sm:inline`}>{occ.label}</span>
                                </>
                            ) : (
                                <span className="text-muted-foreground">--/--</span>
                            )}
                        </p>
                    </div>
                </div>

                <div className={`hidden sm:block h-8 w-px flex-shrink-0 ${dividerClasses}`} />

                {/* Actions */}
                <div className="flex items-center justify-end min-w-[72px] sm:min-w-[90px] flex-shrink-0">
                    {!trip ? (
                        isPast ? (
                            <span className="text-[10px] italic text-muted-foreground/40 leading-tight text-right">
                                Horario<br/>pasado
                            </span>
                        ) : (
                            <Button 
                                variant="outline" 
                                size="sm" 
                                className="gap-1 text-[11px] font-bold h-8 text-blue-700 border-blue-200 hover:bg-blue-50 w-full"
                            >
                                <Plus className="h-3 w-3" />
                                Crear
                            </Button>
                        )
                    ) : (
                        isPastDate ? (
                            <Button
                                variant="outline"
                                size="sm"
                                className="text-[11px] font-bold text-brand-navy h-8 w-full border-brand-navy/20 hover:bg-brand-navy/5"
                                onClick={(e) => { e.stopPropagation(); onViewTrip?.(tripId!) }}
                            >
                                Ver
                            </Button>
                        ) : (
                            <Button
                                variant={isSoldOut ? 'outline' : 'default'}
                                size="sm"
                                disabled={isSoldOut}
                                className={`text-[11px] font-bold uppercase h-8 w-full ${
                                    isSoldOut ? '' : 'bg-brand-navy hover:bg-brand-navy-light'
                                }`}
                                onClick={(e) => { e.stopPropagation(); onSellTicket?.(tripId!) }}
                            >
                                {isSoldOut ? 'Lleno' : 'Vender'}
                            </Button>
                        )
                    )}
                </div>
            </div>

            {/* Bottom row: Meta Info */}
            <div className={`flex items-center flex-wrap gap-x-1.5 gap-y-1 mt-2 pt-2 border-t text-xs ${
                trip ? "border-border/50 text-muted-foreground" : "border-blue-100/30 text-muted-foreground/30"
            }`}>
                <div className="flex items-center gap-1.5 min-w-0 max-w-full">
                    <User className="h-3 w-3 opacity-70 flex-shrink-0" />
                    <span className="truncate">
                        {trip ? "Chofer: " : ""}
                        <span className={`${trip ? "text-foreground font-medium" : "italic"}`}>
                            {driverName}
                        </span>
                    </span>
                </div>
                {trip && assistantName && (
                    <>
                        <span className="text-border/60 hidden sm:inline">|</span>
                        <div className="flex items-center gap-1.5 min-w-0 max-w-full">
                            <Users className="h-3 w-3 opacity-70 flex-shrink-0" />
                            <span className="truncate">
                                Asist: <span className="text-foreground font-medium">{assistantName}</span>
                            </span>
                        </div>
                    </>
                )}
                {trip && (
                    <div className="flex items-center gap-1.5 opacity-50 ml-auto flex-shrink-0">
                        <CalendarClock className="h-3 w-3" />
                        <span className="text-[10px]">ID: {tripId}</span>
                    </div>
                )}
            </div>
        </div>
    )
}

export default function TripCardList({
    scheduleBoard = [],
    loading = false,
    selectedDate = '',
    onViewTrip,
    onCreateTrip,
    onSellTicket,
}: TripCardListProps) {
    const navigate = useNavigate()

    if (loading) {
        return (
            <div role="status" aria-busy="true" className="grid grid-cols-1 xl:grid-cols-2 gap-4 sm:gap-5 lg:gap-6">
                <span className="sr-only">Cargando viajes...</span>
                <div aria-hidden="true">
                {[1, 2].map((n) => (
                    <div key={n} className="space-y-2">
                        <div className="h-6 bg-muted rounded w-2/3 animate-pulse" />
                        <div className="h-3 bg-muted/60 rounded w-1/3 animate-pulse" />
                        {[1, 2, 3].map((m) => (
                            <div key={m} className="h-20 bg-muted/40 rounded-lg animate-pulse" />
                        ))}
                    </div>
                ))}
                </div>
            </div>
        )
    }

    const now = new Date()
    const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
    const isPastDate = selectedDate < todayStr
    const isToday = selectedDate === todayStr
    // Current time as "HH:MM" in local timezone for slot-level comparison
    const currentTimeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`

    if (!scheduleBoard || scheduleBoard.length === 0) {
        return (
            <EmptyState
                title="No hay horarios configurados"
                description="No se encontraron rutas con horarios activos. Configure horarios desde la administración de rutas."
                icon={<CalendarClock className="h-10 w-10 text-muted-foreground" />}
                action={
                    <Button onClick={() => navigate(ROUTES.ADMIN.ROUTES)} className="gap-2">
                        <Settings className="h-4 w-4" />
                        Configurar Rutas
                    </Button>
                }
            />
        )
    }

    return (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 sm:gap-5 lg:gap-6">
            {scheduleBoard.map((group) => (
                <div key={group.route.id} className="space-y-2">
                    {/* Route Header */}
                    <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                            <h2 className="text-sm sm:text-base lg:text-lg font-bold text-foreground break-words">
                                {group.route.origin} <span className="text-muted-foreground mx-1">→</span> {group.route.destination}
                            </h2>
                            <p className="text-[11px] sm:text-xs text-muted-foreground truncate">Salidas desde {group.route.origin}</p>
                        </div>
                        <Badge variant="outline" className="text-[10px] font-semibold uppercase tracking-wider border-brand-navy text-brand-navy whitespace-nowrap flex-shrink-0">
                            {group.slots.length} Horarios
                        </Badge>
                    </div>

                    {/* Trip Rows */}
                    <div className="space-y-2">
                        {group.slots.map((slot) => (
                            <TripRow
                                key={`${group.route.id}-${slot.time}`}
                                slot={slot}
                                onViewTrip={onViewTrip}
                                onSellTicket={onSellTicket}
                                onCreateTrip={onCreateTrip}
                                selectedDate={selectedDate}
                                isPastDate={isPastDate}
                                isSlotPast={isToday && slot.time < currentTimeStr}
                            />
                        ))}
                    </div>
                </div>
            ))}
        </div>
    )
}

// frontend/components/trips/TripCardList.vue
<template>
  <div>
    <!-- Loading State -->
    <div v-if="loading" class="space-y-6">
      <div v-for="n in 2" :key="n" class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
        <div class="px-6 py-4 bg-gradient-to-r from-indigo-50 to-purple-50 border-b border-gray-200 animate-pulse">
          <div class="h-6 bg-gray-200 rounded w-1/3"></div>
        </div>
        <div class="p-4">
          <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            <div v-for="m in 3" :key="m" class="bg-white shadow-md rounded-xl border border-gray-100 p-6 animate-pulse">
              <div class="flex justify-between items-start mb-4">
                <div class="flex-1">
                  <div class="h-6 bg-gray-200 rounded w-3/4 mb-2"></div>
                  <div class="h-4 bg-gray-200 rounded w-1/2"></div>
                </div>
                <div class="h-6 bg-gray-200 rounded-full w-20"></div>
              </div>
              <div class="h-4 bg-gray-200 rounded w-full mb-2"></div>
              <div class="h-4 bg-gray-200 rounded w-3/4"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Empty State (no routes with schedules) -->
    <EmptyState
      v-else-if="!scheduleBoard || scheduleBoard.length === 0"
      title="No hay horarios configurados"
      description="No se encontraron rutas con horarios activos. Configure horarios desde la administracion de rutas."
    >
      <template #icon>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </template>
      <template #action>
        <button @click="navigateTo('/admin/routes')" class="inline-flex items-center px-4 py-2 border border-transparent rounded-lg text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 transition-colors">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          Configurar Rutas
        </button>
      </template>
    </EmptyState>

    <!-- Schedule Board -->
    <div v-else class="space-y-6">
      <div
        v-for="group in scheduleBoard"
        :key="group.route.id"
        class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"
      >
        <!-- Route Group Header -->
        <button
          @click="toggleRouteGroup(group.route.id)"
          class="w-full flex items-center justify-between px-6 py-4 bg-gradient-to-r from-indigo-50 to-purple-50 border-b border-gray-200 hover:from-indigo-100 hover:to-purple-100 transition-colors"
        >
          <div class="flex items-center space-x-3">
            <div class="flex items-center justify-center w-10 h-10 bg-gradient-to-r from-indigo-600 to-purple-700 rounded-xl shadow-sm">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
              </svg>
            </div>
            <div class="text-left">
              <h3 class="text-lg font-bold text-gray-900">
                {{ group.route.origin }}
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline mx-1 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
                {{ group.route.destination }}
              </h3>
              <p class="text-sm text-gray-600">
                {{ group.slots.length }} horario{{ group.slots.length !== 1 ? 's' : '' }}
                &middot;
                {{ countTripsInGroup(group) }} viaje{{ countTripsInGroup(group) !== 1 ? 's' : '' }} creado{{ countTripsInGroup(group) !== 1 ? 's' : '' }}
              </p>
            </div>
          </div>
          <div class="flex items-center space-x-3">
            <!-- Progress badge -->
            <span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold"
              :class="countTripsInGroup(group) === group.slots.length 
                ? 'bg-green-100 text-green-800' 
                : 'bg-orange-100 text-orange-800'"
            >
              {{ countTripsInGroup(group) }}/{{ group.slots.length }}
            </span>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 text-gray-500 transition-transform duration-200"
              :class="{ 'rotate-180': isRouteExpanded(group.route.id) }"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </button>

        <!-- Route Group Content -->
        <div v-if="isRouteExpanded(group.route.id)" class="p-4">
          <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            <template v-for="slot in group.slots" :key="`${group.route.id}-${slot.time}`">
              <!-- Existing Trip Card -->
              <TripCard
                v-if="slot.trip"
                :trip="slot.trip"
                @view-trip="$emit('view-trip', $event)"
                @edit-trip="$emit('edit-trip', $event)"
              />

              <!-- Empty Slot Card -->
              <div
                v-else
                class="bg-white rounded-2xl border-2 border-dashed border-gray-300 p-4 lg:p-6 flex flex-col justify-between hover:border-indigo-400 hover:bg-indigo-50/30 transition-all duration-300 group cursor-pointer"
                @click="$emit('create-trip', { routeId: slot.route.id, date: selectedDate, time: slot.time })"
              >
                <!-- Time Header -->
                <div>
                  <div class="flex justify-between items-start mb-4">
                    <div class="flex items-center space-x-3">
                      <div class="flex items-center justify-center w-10 h-10 bg-gray-100 group-hover:bg-indigo-100 rounded-xl transition-colors">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400 group-hover:text-indigo-600 transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      </div>
                      <div>
                        <p class="text-2xl font-bold text-gray-900">{{ slot.time }}</p>
                        <p class="text-sm text-gray-500">Horario programado</p>
                      </div>
                    </div>
                    <span class="px-3 py-1.5 inline-flex items-center text-xs leading-5 font-semibold rounded-full border bg-gray-50 text-gray-600 border-gray-200">
                      <span class="w-2 h-2 rounded-full mr-2 bg-gray-400"></span>
                      Sin viaje
                    </span>
                  </div>

                  <!-- Route info -->
                  <div class="bg-gray-50 rounded-lg p-3 border border-gray-200 mb-4">
                    <div class="flex items-center space-x-2 text-sm text-gray-700">
                      <span class="font-medium">{{ slot.route.origin }}</span>
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                      </svg>
                      <span class="font-medium">{{ slot.route.destination }}</span>
                    </div>
                    <p v-if="slot.route.price" class="text-xs text-gray-500 mt-1">
                      Precio: {{ formatCurrency(slot.route.price) }}
                    </p>
                  </div>
                </div>

                <!-- Create Trip Button -->
                <div class="pt-4 border-t border-gray-200 mt-auto">
                  <button
                    class="w-full inline-flex items-center justify-center px-4 py-3 text-sm font-medium text-indigo-700 bg-indigo-50 border border-indigo-200 rounded-xl hover:bg-indigo-100 hover:border-indigo-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition-all duration-200 group-hover:bg-indigo-100 group-hover:border-indigo-300"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                    Crear Viaje
                  </button>
                </div>
              </div>
            </template>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { reactive } from 'vue';
import { navigateTo } from '#app';
import TripCard from './TripCard.vue';
import EmptyState from '~/components/common/EmptyState.vue';

const props = defineProps({
  scheduleBoard: {
    type: Array,
    default: () => [],
  },
  loading: {
    type: Boolean,
    default: false,
  },
  selectedDate: {
    type: String,
    default: '',
  },
});

const emit = defineEmits(['view-trip', 'edit-trip', 'create-trip']);

// Track explicitly collapsed routes (all expanded by default)
const collapsedRoutes = reactive({});

// Groups are expanded unless explicitly collapsed
const isRouteExpanded = (routeId) => {
  return collapsedRoutes[routeId] !== true;
};

const toggleRouteGroup = (routeId) => {
  collapsedRoutes[routeId] = !collapsedRoutes[routeId];
};

const countTripsInGroup = (group) => {
  return group.slots.filter(slot => slot.trip !== null).length;
};

const formatCurrency = (amount) => {
  if (!amount) return '';
  return new Intl.NumberFormat('es-BO', {
    style: 'currency',
    currency: 'BOB',
    minimumFractionDigits: 2,
  }).format(amount);
};
</script>
