// frontend/components/TicketDisplay.vue
<template>
  <div 
    class="ticket-container bg-white rounded-lg overflow-hidden mx-auto"
    :class="previewMode 
      ? 'border-2 border-blue-300 max-w-md shadow-md scale-90 transform origin-top' 
      : 'border-4 border-blue-400 max-w-4xl shadow-2xl'"
  >
    <!-- Header principal con logo y información de la empresa -->
    <div 
      class="ticket-header bg-gradient-to-r from-cyan-400 to-blue-500 text-white"
      :class="previewMode 
        ? 'px-2 py-1 border-b-2 border-blue-500' 
        : 'px-4 py-3 border-b-4 border-blue-600'"
    >
      <div class="flex items-start justify-between">
        <!-- Lado izquierdo: Logo del bus y texto -->
        <div class="flex items-start space-x-3">
          <!-- Logo del bus -->
          <div class="flex-shrink-0">
            <svg 
              class="text-white" 
              :class="previewMode ? 'w-8 h-6' : 'w-16 h-12'"
              fill="currentColor" 
              viewBox="0 0 100 60"
            >
              <rect x="10" y="20" width="70" height="25" rx="5" fill="currentColor"/>
              <rect x="15" y="15" width="60" height="8" rx="3" fill="currentColor"/>
              <circle cx="25" cy="50" r="6" fill="currentColor"/>
              <circle cx="65" cy="50" r="6" fill="currentColor"/>
              <rect x="20" y="25" width="8" height="6" fill="white"/>
              <rect x="32" y="25" width="8" height="6" fill="white"/>
              <rect x="44" y="25" width="8" height="6" fill="white"/>
              <rect x="56" y="25" width="8" height="6" fill="white"/>
            </svg>
          </div>
          
          <!-- Texto principal -->
          <div>
            <div class="flex items-baseline space-x-2 mb-1">
              <h1 :class="previewMode ? 'text-lg font-bold' : 'text-2xl font-bold'">TRANS</h1>
              <h2 :class="previewMode ? 'text-lg font-bold italic' : 'text-2xl font-bold italic'">Comarapa</h2>
            </div>
            <div class="leading-tight" :class="previewMode ? 'text-xs' : 'text-xs'">
              <p class="font-medium">SINDICATO MIXTO DE TRANSPORTISTAS DE LARGA</p>
              <p class="font-medium">Y CORTA DISTANCIA "MANUEL MARIA CABALLERO"</p>
            </div>
          </div>
        </div>
        
        <!-- Centro: Resolución -->
        <div class="text-center">
          <p :class="previewMode ? 'text-xs font-bold' : 'text-sm font-bold'">Resolución Suprema 17996</p>
        </div>
        
        <!-- Lado derecho: Águila -->
        <div class="flex-shrink-0">
          <svg 
            class="text-white" 
            :class="previewMode ? 'w-8 h-8' : 'w-16 h-16'" 
            fill="currentColor" 
            viewBox="0 0 100 100"
          >
            <path d="M50 10 L30 30 L20 50 L30 60 L50 55 L70 60 L80 50 L70 30 Z"/>
            <path d="M50 15 L40 25 L50 35 L60 25 Z"/>
            <circle cx="45" cy="25" r="2"/>
            <circle cx="55" cy="25" r="2"/>
          </svg>
        </div>
      </div>
      
      <!-- Información de oficinas -->
      <div 
        class="grid grid-cols-2 gap-x-8"
        :class="previewMode ? 'mt-1 text-xs' : 'mt-2 text-xs'"
      >
        <div>
          <p><span class="font-medium">Of. Santa Cruz:</span> Av. Doble Vía La Guardia 4to. Anillo • <span class="font-medium">Cel.:</span> 781-75576</p>
          <p><span class="font-medium">Of. Comarapa:</span> Av. Comarapa • <span class="font-medium">Cel.:</span> 781-75578</p>
        </div>
        <div>
          <p><span class="font-medium">Of. San Isidro:</span> <span class="font-medium">Cel.:</span> 785-15650</p>
          <p><span class="font-medium">Of. Los Negros:</span> <span class="font-medium">Cel.:</span> 690-29690</p>
        </div>
      </div>
    </div>

    <!-- Área principal del boleto -->
    <div class="bg-white relative">
      <!-- Boleto label en la esquina superior derecha -->
      <div 
        class="absolute right-4"
        :class="previewMode ? 'top-1' : 'top-2'"
      >
        <div 
          class="bg-blue-500 text-white rounded-lg"
          :class="previewMode ? 'px-3 py-1' : 'px-6 py-2'"
        >
          <h3 
            class="font-bold"
            :class="previewMode ? 'text-sm' : 'text-xl'"
          >
            BOLETO
          </h3>
        </div>
      </div>

      <div :class="previewMode ? 'px-3 py-2 pt-8' : 'px-4 py-4 pt-16'">
        <!-- Fila NOMBRE y N° -->
        <div 
          :class="previewMode ? 'border-2 border-blue-400 mb-2' : 'border-4 border-blue-500 mb-2'"
        >
          <div class="flex">
            <!-- NOMBRE -->
            <div 
              class="bg-blue-500 text-white font-bold"
              :class="previewMode ? 'px-3 py-2 text-base' : 'px-4 py-3 text-lg'"
            >
              NOMBRE:
            </div>
            <!-- Espacio para el nombre -->
            <div 
              class="flex-grow bg-white text-gray-700"
              :class="previewMode 
                ? 'border-r-2 border-blue-400 px-3 py-2 text-base' 
                : 'border-r-4 border-blue-500 px-4 py-3'"
            >
              {{ getFullName() }}
            </div>
            <!-- N° -->
            <div 
              class="bg-white text-right"
              :class="previewMode ? 'px-3 py-2' : 'px-6 py-3'"
            >
              <span 
                class="text-red-600 font-bold"
                :class="previewMode ? 'text-lg' : 'text-2xl'"
              >
                N° {{ ticket.id || '115032' }}
              </span>
            </div>
          </div>
        </div>

        <!-- Fila Bs, Destino, N° -->
        <div 
          class="grid grid-cols-12"
          :class="previewMode ? 'gap-2 mb-2' : 'gap-2 mb-2'"
        >
          <!-- Bs. -->
          <div 
            class="col-span-2"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-sm' : 'py-2'"
            >
              Bs.
            </div>
            <div 
              class="bg-white text-center font-bold"
              :class="previewMode ? 'py-2 text-base' : 'py-4 text-xl'"
            >
              {{ formatPrice(ticket.price) }}
            </div>
          </div>

          <!-- Destino -->
          <div 
            class="col-span-7"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-sm' : 'py-2'"
            >
              Destino:
            </div>
            <div 
              class="bg-white text-center font-bold"
              :class="previewMode ? 'py-2 text-base' : 'py-4 text-lg'"
            >
              {{ getDestination() }}
            </div>
          </div>

          <!-- N° -->
          <div 
            class="col-span-3"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-sm' : 'py-2'"
            >
              N°
            </div>
            <div 
              class="bg-white text-center font-bold"
              :class="[
                previewMode ? 'py-2 text-base' : 'py-4',
                getSeatNumberClass()
              ]"
            >
              {{ getSeatNumbers() }}
            </div>
          </div>
        </div>

        <!-- Fila Fecha y Horarios -->
        <div 
          class="grid grid-cols-12 mb-4"
          :class="previewMode ? 'gap-1' : 'gap-2'"
        >
          <!-- Fecha -->
          <div 
            class="col-span-4"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-xs' : 'py-2'"
            >
              Fecha
            </div>
            <div :class="previewMode ? 'bg-white p-1' : 'bg-white p-2'">
              <div class="grid grid-cols-3 gap-1">
                <div 
                  class="border-2 border-blue-300 text-center font-bold"
                  :class="previewMode ? 'py-1 text-xs' : 'py-2'"
                >
                  {{ getDayFromDate() }}
                </div>
                <div 
                  class="border-2 border-blue-300 text-center font-bold"
                  :class="previewMode ? 'py-1 text-xs' : 'py-2'"
                >
                  {{ getMonthFromDate() }}
                </div>
                <div 
                  class="border-2 border-blue-300 text-center font-bold"
                  :class="previewMode ? 'py-1 text-xs' : 'py-2'"
                >
                  {{ getYearFromDate() }}
                </div>
              </div>
            </div>
          </div>

          <!-- Hora en Oficina -->
          <div 
            class="col-span-4"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-xs' : 'py-2'"
            >
              Hora en Oficina:
            </div>
            <div :class="previewMode ? 'bg-white p-1' : 'bg-white p-2'">
              <div 
                class="flex justify-center mb-2"
                :class="previewMode ? 'space-x-1' : 'space-x-2'"
              >
                <span 
                  class="bg-blue-100 rounded font-bold text-blue-600"
                  :class="previewMode ? 'px-1 py-0.5 text-xs' : 'px-3 py-1'"
                >
                  AM
                </span>
                <span 
                  class="bg-blue-100 rounded font-bold text-blue-600"
                  :class="previewMode ? 'px-1 py-0.5 text-xs' : 'px-3 py-1'"
                >
                  PM
                </span>
              </div>
              <div 
                class="text-center font-bold"
                :class="previewMode ? 'text-xs' : 'text-lg'"
              >
                {{ getCurrentTime() }}
              </div>
            </div>
          </div>

          <!-- Hora Salida -->
          <div 
            class="col-span-4"
            :class="previewMode ? 'border-2 border-blue-400' : 'border-4 border-blue-500'"
          >
            <div 
              class="bg-blue-500 text-white text-center font-bold"
              :class="previewMode ? 'py-1 text-xs' : 'py-2'"
            >
              Hora Salida:
            </div>
            <div :class="previewMode ? 'bg-white p-1' : 'bg-white p-2'">
              <div 
                class="flex justify-center mb-2"
                :class="previewMode ? 'space-x-1' : 'space-x-2'"
              >
                <span 
                  class="bg-blue-100 rounded font-bold text-blue-600"
                  :class="previewMode ? 'px-1 py-0.5 text-xs' : 'px-3 py-1'"
                >
                  AM
                </span>
                <span 
                  class="bg-blue-100 rounded font-bold text-blue-600"
                  :class="previewMode ? 'px-1 py-0.5 text-xs' : 'px-3 py-1'"
                >
                  PM
                </span>
              </div>
              <div 
                class="text-center font-bold"
                :class="previewMode ? 'text-xs' : 'text-lg'"
              >
                {{ getDepartureTime() }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div 
      class="bg-gradient-to-r from-cyan-400 to-blue-500 text-white"
      :class="previewMode 
        ? 'px-2 py-1 border-t-2 border-blue-500' 
        : 'px-4 py-3 border-t-4 border-blue-600'"
    >
              <div :class="previewMode ? 'grid grid-cols-12 gap-1' : 'grid grid-cols-12 gap-4'">
          <!-- NO SE ACEPTAN DEVOLUCIONES -->
          <div class="col-span-4">
            <div class="text-center">
              <p 
                class="font-bold mb-1"
                :class="previewMode ? 'text-xs' : 'text-lg'"
              >
                NO SE ACEPTAN
              </p>
              <p 
                class="font-bold mb-2"
                :class="previewMode ? 'text-xs' : 'text-lg'"
              >
                DEVOLUCIONES
              </p>
              <p 
                class="italic"
                :class="previewMode ? 'text-xs' : 'text-sm'"
              >
                Gracias por su preferencia!!!
              </p>
            </div>
          </div>

          <!-- HORARIOS -->
          <div class="col-span-8">
            <div 
              class="bg-blue-600 rounded"
              :class="previewMode ? 'px-1 py-1' : 'px-3 py-2'"
            >
              <h4 
                class="text-center font-bold mb-2"
                :class="previewMode ? 'text-xs' : 'text-sm'"
              >
                HORARIOS DE SALIDA DE SANTA CRUZ A COMARAPA
              </h4>
              <div 
                class="leading-tight"
                :class="previewMode ? 'text-xs' : 'text-xs'"
              >
                <p><span class="font-bold">De lunes a Jueves son:</span> 10:30 am., 14:00 pm., 18:30 pm., 20:30 pm.</p>
                <p><span class="font-bold">Solo viernes sábado y domingo:</span></p>
                <p>10:30 am., 14:00 pm., 18:30 pm., 20:30 pm., 22:00 pm.</p>
                <p><span class="font-bold">DE COMARAPA A SANTA CRUZ</span> de Lunes a Sábado son:</p>
                <p>8:00 am., 14:00 pm., 20:30 pm., 23:30 pm.</p>
                <p><span class="font-bold">Solo domingo:</span> 8:30 am., 12:00 del medio día, 14:00 pm., 20:30 pm., 23:30 pm.</p>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  ticket: {
    type: Object,
    required: true
  },
  trip: {
    type: Object,
    required: true
  },
  previewMode: {
    type: Boolean,
    default: false
  }
})

// Computed properties para formatear la información
const formatPrice = (price) => {
  return price ? parseFloat(price).toFixed(2) : '0.00'
}

const getDestination = () => {
  if (props.trip?.route?.destination) {
    return props.trip.route.destination
  }
  return props.ticket.trip?.route?.destination || 'Destino'
}

const getFullName = () => {
  const client = props.ticket.client
  if (client) {
    return `${client.firstname || ''} ${client.lastname || ''}`.trim()
  }
  return 'Cliente'
}

const getDayFromDate = () => {
  const date = props.trip?.trip_datetime || props.ticket.trip?.trip_datetime
  if (date) {
    return new Date(date).getDate().toString().padStart(2, '0')
  }
  return new Date().getDate().toString().padStart(2, '0')
}

const getMonthFromDate = () => {
  const date = props.trip?.trip_datetime || props.ticket.trip?.trip_datetime
  if (date) {
    return (new Date(date).getMonth() + 1).toString().padStart(2, '0')
  }
  return (new Date().getMonth() + 1).toString().padStart(2, '0')
}

const getYearFromDate = () => {
  const date = props.trip?.trip_datetime || props.ticket.trip?.trip_datetime
  if (date) {
    return new Date(date).getFullYear().toString().slice(-2)
  }
  return new Date().getFullYear().toString().slice(-2)
}

const getCurrentTime = () => {
  const now = new Date()
  return now.toLocaleTimeString('es-BO', { 
    hour: '2-digit', 
    minute: '2-digit',
    hour12: false 
  })
}

const getDepartureTime = () => {
  const datetime = props.trip?.trip_datetime || props.ticket.trip?.trip_datetime
  if (datetime) {
    const date = new Date(datetime)
    return date.toLocaleTimeString('es-BO', { 
      hour: '2-digit', 
      minute: '2-digit',
      hour12: false 
    })
  }
  return '00:00'
}

const getSeatNumberClass = () => {
  // Manejar múltiples asientos
  let seatNumbers = ''
  if (props.ticket.seats && Array.isArray(props.ticket.seats)) {
    seatNumbers = props.ticket.seats.map(seat => seat.seat_number).join(', ')
  } else if (props.ticket.seat?.seat_number) {
    seatNumbers = props.ticket.seat.seat_number.toString()
  } else {
    seatNumbers = '36'
  }
  
  // Si hay múltiples asientos (contiene comas) o el texto es muy largo
  if (seatNumbers.includes(',') || seatNumbers.length > 4) {
    return props.previewMode ? 'text-sm leading-tight' : 'text-lg leading-tight' // Texto más pequeño para múltiples asientos
  } else if (seatNumbers.length > 2) {
    return props.previewMode ? 'text-base' : 'text-xl' // Texto mediano para números de 3-4 dígitos
  } else {
    return props.previewMode ? 'text-lg' : 'text-2xl' // Texto grande para números cortos (1-2 dígitos)
  }
}

const getSeatNumbers = () => {
  if (props.ticket.seats && Array.isArray(props.ticket.seats)) {
    return props.ticket.seats.map(seat => seat.seat_number).join(', ')
  } else if (props.ticket.seat?.seat_number) {
    return props.ticket.seat.seat_number
  } else {
    return '36'
  }
}
</script>

<style scoped>
.ticket-container {
  font-family: 'Arial', sans-serif;
  max-width: 950px;
  background: white;
}

.ticket-header {
  background: linear-gradient(135deg, #00bcd4 0%, #2196f3 100%);
}

.ticket-footer {
  background: linear-gradient(135deg, #00bcd4 0%, #2196f3 100%);
}

/* Bordes azules específicos */
.border-blue-500 {
  border-color: #3b82f6;
}

.border-blue-600 {
  border-color: #2563eb;
}

.border-blue-400 {
  border-color: #60a5fa;
}

.bg-blue-500 {
  background-color: #3b82f6;
}

.bg-blue-600 {
  background-color: #2563eb;
}

/* Grid sistema para layout horizontal */
.grid-cols-12 {
  grid-template-columns: repeat(12, minmax(0, 1fr));
}

/* Print styles */
@media print {
  .ticket-container {
    max-width: none;
    width: 210mm;
    box-shadow: none;
    border: 2px solid #000;
    margin: 0;
  }
  
  .bg-gradient-to-r,
  .bg-gradient-to-l,
  .bg-blue-500,
  .bg-blue-600 {
    background: #3b82f6 !important;
    -webkit-print-color-adjust: exact;
    color-adjust: exact;
  }
  
  .border-4 {
    border-width: 2px !important;
  }
  
  .text-xs {
    font-size: 10px !important;
  }
  
  .text-sm {
    font-size: 12px !important;
  }
  
  .text-base {
    font-size: 14px !important;
  }
  
  .text-lg {
    font-size: 16px !important;
  }
  
  .text-xl {
    font-size: 18px !important;
  }
  
  .text-2xl {
    font-size: 20px !important;
  }
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .ticket-container {
    max-width: 100%;
    margin: 0;
  }
  
  .grid-cols-12 {
    display: block;
  }
  
  .col-span-2,
  .col-span-3,
  .col-span-4,
  .col-span-5,
  .col-span-7,
  .col-span-8 {
    width: 100%;
    margin-bottom: 0.5rem;
  }
  
  .text-xl {
    font-size: 1.125rem;
  }
  
  .text-lg {
    font-size: 1rem;
  }
  
  .px-6 {
    padding-left: 1rem;
    padding-right: 1rem;
  }
  
  .flex {
    flex-direction: column;
  }
  
  .flex-grow {
    flex-grow: initial;
  }
}

@media (max-width: 480px) {
  .grid-cols-2 {
    grid-template-columns: 1fr;
    gap: 0.5rem;
  }
  
  .grid-cols-3 {
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 0.25rem;
  }
  
  .text-sm {
    font-size: 0.75rem;
  }
  
  .px-4 {
    padding-left: 0.75rem;
    padding-right: 0.75rem;
  }
  
  .border-4 {
    border-width: 2px;
  }
}

/* Ensure proper spacing for horizontal layout */
.col-span-1 { grid-column: span 1 / span 1; }
.col-span-2 { grid-column: span 2 / span 2; }
.col-span-3 { grid-column: span 3 / span 3; }
.col-span-4 { grid-column: span 4 / span 4; }
.col-span-5 { grid-column: span 5 / span 5; }
.col-span-6 { grid-column: span 6 / span 6; }
.col-span-7 { grid-column: span 7 / span 7; }
.col-span-8 { grid-column: span 8 / span 8; }
.col-span-9 { grid-column: span 9 / span 9; }
.col-span-10 { grid-column: span 10 / span 10; }
.col-span-11 { grid-column: span 11 / span 11; }
.col-span-12 { grid-column: span 12 / span 12; }

/* Bordes gruesos específicos */
.border-4 {
  border-width: 4px;
}

.border-2 {
  border-width: 2px;
}

/* Colores de texto específicos */
.text-red-600 {
  color: #dc2626;
}

.text-blue-600 {
  color: #2563eb;
}

.text-gray-700 {
  color: #374151;
}

/* Flexbox específico para el layout del nombre */
.flex-grow {
  flex-grow: 1;
}

.flex-shrink-0 {
  flex-shrink: 0;
}
</style>

// frontend-react/src/components/tickets/TicketDisplay.tsx
export default function TicketDisplay({
    ticket,
    trip,
    previewMode = false
}: {
    ticket: any
    trip: any
    previewMode?: boolean
}) {
    const formatPrice = (price?: number | string) => price ? parseFloat(price.toString()).toFixed(2) : '0.00'

    const getDestination = () => {
        if (ticket?.destination) return ticket.destination
        if (trip?.route?.destination) return trip.route.destination
        return ticket?.trip?.route?.destination || 'Destino'
    }

    const getFullName = () => {
        const client = ticket?.client
        if (client) return `${client.firstname || ''} ${client.lastname || ''}`.trim()
        return 'Cliente'
    }

    const getDateObj = () => {
        const d = trip?.trip_datetime || ticket?.trip?.trip_datetime
        return d ? new Date(d) : new Date()
    }

    const getDayFromDate = () => getDateObj().getDate().toString().padStart(2, '0')
    const getMonthFromDate = () => (getDateObj().getMonth() + 1).toString().padStart(2, '0')
    const getYearFromDate = () => getDateObj().getFullYear().toString().slice(-2)

    const getOfficeTimeObj = () => {
        const d = getDateObj()
        return new Date(d.getTime() - 30 * 60 * 1000)
    }

    const getCurrentTime = () => {
        return getOfficeTimeObj().toLocaleTimeString('es-BO', {
            hour: '2-digit', minute: '2-digit', hour12: false
        })
    }

    const getDepartureTime = () => {
        return getDateObj().toLocaleTimeString('es-BO', {
            hour: '2-digit', minute: '2-digit', hour12: false
        })
    }

    const getOfficeTimeAmPm = () => getOfficeTimeObj().getHours() < 12 ? 'AM' : 'PM'
    const getDepartureTimeAmPm = () => getDateObj().getHours() < 12 ? 'AM' : 'PM'

    const getSeatNumbers = () => {
        if (ticket?.seats && Array.isArray(ticket.seats)) {
            return ticket.seats.map((s: any) => s.seat_number).join(', ')
        } else if (ticket?.seat?.seat_number) {
            return ticket.seat.seat_number
        }
        return '36'
    }

    const getSeatNumberClass = () => {
        const nums = getSeatNumbers()
        if (nums.toString().includes(',') || nums.toString().length > 4) {
            return previewMode ? 'text-sm leading-tight' : 'text-lg leading-tight'
        } else if (nums.toString().length > 2) {
            return previewMode ? 'text-base' : 'text-xl'
        }
        return previewMode ? 'text-lg' : 'text-2xl'
    }

    return (
        <div className={`bg-white rounded-lg overflow-hidden mx-auto font-sans print:max-w-none print:w-[210mm] print:shadow-none print:border-2 print:border-black print:m-0 ${previewMode ? 'border-2 border-blue-300 max-w-md shadow-md scale-90 transform origin-top' : 'border-4 border-blue-400 max-w-4xl shadow-2xl'}`}>
            <div className={`bg-gradient-to-r from-cyan-400 to-blue-500 text-white print:bg-blue-500 print:!bg-none ${previewMode ? 'px-2 py-1 border-b-2 border-blue-500' : 'px-4 py-3 border-b-4 border-blue-600'}`}>
                <div className="flex items-start justify-between">
                    <div className="flex items-start space-x-3">
                        <div className="flex-shrink-0">
                            <svg className={`text-white ${previewMode ? 'w-8 h-6' : 'w-16 h-12'}`} fill="currentColor" viewBox="0 0 100 60">
                                <rect x="10" y="20" width="70" height="25" rx="5" fill="currentColor" />
                                <rect x="15" y="15" width="60" height="8" rx="3" fill="currentColor" />
                                <circle cx="25" cy="50" r="6" fill="currentColor" />
                                <circle cx="65" cy="50" r="6" fill="currentColor" />
                                <rect x="20" y="25" width="8" height="6" fill="white" />
                                <rect x="32" y="25" width="8" height="6" fill="white" />
                                <rect x="44" y="25" width="8" height="6" fill="white" />
                                <rect x="56" y="25" width="8" height="6" fill="white" />
                            </svg>
                        </div>
                        <div>
                            <div className="flex items-baseline mb-0">
                                <h1 className={previewMode ? 'text-base font-bold mr-1' : 'text-2xl font-bold space-x-2'}>TRANS</h1>
                                <h2 className={previewMode ? 'text-base font-bold italic' : 'text-2xl font-bold italic'}>Comarapa</h2>
                            </div>
                            <div className={`leading-none ${previewMode ? 'text-[8px]' : 'text-xs'}`}>
                                <p className="font-medium">SINDICATO MIXTO DE TRANSPORTISTAS DE LARGA</p>
                                <p className="font-medium">Y CORTA DISTANCIA "MANUEL MARIA CABALLERO"</p>
                            </div>
                        </div>
                    </div>
                    <div className="text-center">
                        <p className={previewMode ? 'text-xs font-bold' : 'text-sm font-bold'}>Resolución Suprema 17996</p>
                    </div>
                    <div className="flex-shrink-0">
                        <svg className={`text-white ${previewMode ? 'w-6 h-6' : 'w-16 h-16'}`} fill="currentColor" viewBox="0 0 100 100">
                            <path d="M50 10 L30 30 L20 50 L30 60 L50 55 L70 60 L80 50 L70 30 Z" />
                            <path d="M50 15 L40 25 L50 35 L60 25 Z" />
                            <circle cx="45" cy="25" r="2" />
                            <circle cx="55" cy="25" r="2" />
                        </svg>
                    </div>
                </div>
                <div className={`grid grid-cols-2 gap-x-4 ${previewMode ? 'mt-0 text-[8px] leading-tight pb-1' : 'mt-2 text-xs gap-x-8'}`}>
                    <div>
                        <p><span className="font-medium">Of. Santa Cruz:</span> Doble Vía La Guardia 4to <span className="font-medium">Cel:</span> 781-75576</p>
                        <p><span className="font-medium">Of. Comarapa:</span> Av. Comarapa • <span className="font-medium">Cel:</span> 781-75578</p>
                    </div>
                    <div>
                        <p><span className="font-medium">Of. San Isidro:</span> <span className="font-medium">Cel:</span> 785-15650</p>
                        <p><span className="font-medium">Of. Los Negros:</span> <span className="font-medium">Cel:</span> 690-29690</p>
                    </div>
                </div>
            </div>

            <div className="bg-white relative">
                <div className={`absolute right-4 ${previewMode ? 'top-1' : 'top-2'}`}>
                    <div className={`bg-blue-500 text-white rounded-lg print:bg-blue-500 ${previewMode ? 'px-3 py-1' : 'px-6 py-2'}`}>
                        <h3 className={`font-bold ${previewMode ? 'text-sm' : 'text-xl'}`}>BOLETO</h3>
                    </div>
                </div>

                <div className={previewMode ? 'px-3 py-1 pt-6' : 'px-4 py-4 pt-16'}>
                    <div className={previewMode ? 'border-2 border-blue-400 mb-1' : 'border-4 border-blue-500 mb-2'}>
                        <div className="flex">
                            <div className={`bg-blue-500 text-white font-bold print:bg-blue-500 ${previewMode ? 'px-2 py-1 text-xs flex items-center' : 'px-4 py-3 text-lg'}`}>
                                NOMBRE:
                            </div>
                            <div className={`flex-grow bg-white text-gray-700 font-bold ${previewMode ? 'border-r-2 border-blue-400 px-2 py-1 text-xs flex items-center' : 'border-r-4 border-blue-500 px-4 py-3'}`}>
                                {getFullName()}
                            </div>
                            <div className={`bg-white text-right ${previewMode ? 'px-2 py-1 flex items-center' : 'px-6 py-3'}`}>
                                <span className={`text-red-600 font-bold ${previewMode ? 'text-sm' : 'text-2xl'}`}>
                                    N° {ticket?.id || '115032'}
                                </span>
                            </div>
                        </div>
                    </div>

                    <div className={`grid grid-cols-12 ${previewMode ? 'gap-1 mb-1' : 'gap-2 mb-2'}`}>
                        <div className={`col-span-2 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>Bs.</div>
                            <div className={`bg-white text-center font-bold flex-1 flex items-center justify-center ${previewMode ? 'py-1 text-sm' : 'py-4 text-xl'}`}>{formatPrice(ticket?.price)}</div>
                        </div>
                        <div className={`col-span-7 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>Destino:</div>
                            <div className={`bg-white text-center font-bold flex-1 flex items-center justify-center ${previewMode ? 'py-1 text-sm line-clamp-1' : 'py-4 text-lg'}`}>{getDestination()}</div>
                        </div>
                        <div className={`col-span-3 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>N°</div>
                            <div className={`bg-white text-center font-bold text-red-600 flex-1 flex items-center justify-center ${previewMode ? 'py-1 text-base' : 'py-4'} ${getSeatNumberClass()}`}>{getSeatNumbers()}</div>
                        </div>
                    </div>

                    <div className={`grid grid-cols-12 mb-2 ${previewMode ? 'gap-1' : 'gap-2'}`}>
                        <div className={`col-span-4 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>Fecha</div>
                            <div className={previewMode ? 'bg-white p-1 flex-1 flex flex-col justify-center' : 'bg-white p-2'}>
                                <div className="grid grid-cols-3 gap-1">
                                    <div className={`border-2 border-blue-300 text-center font-bold flex items-center justify-center ${previewMode ? 'py-1 text-xs' : 'py-2'}`}>{getDayFromDate()}</div>
                                    <div className={`border-2 border-blue-300 text-center font-bold flex items-center justify-center ${previewMode ? 'py-1 text-xs' : 'py-2'}`}>{getMonthFromDate()}</div>
                                    <div className={`border-2 border-blue-300 text-center font-bold flex items-center justify-center ${previewMode ? 'py-1 text-xs' : 'py-2'}`}>{getYearFromDate()}</div>
                                </div>
                            </div>
                        </div>
                        <div className={`col-span-4 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold leading-tight print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>Hora en Of.:</div>
                            <div className={previewMode ? 'bg-white flex flex-row items-center justify-center space-x-2 py-2 flex-1' : 'bg-white p-2'}>
                                <div className={`flex justify-center ${previewMode ? '' : 'mb-2'}`}>
                                    <span className={`bg-blue-100 rounded font-bold text-blue-600 ${previewMode ? 'px-1 py-0.5 text-[10px]' : 'px-3 py-1'}`}>{getOfficeTimeAmPm()}</span>
                                </div>
                                <div className={`text-center font-bold text-red-600 ${previewMode ? 'text-sm' : 'text-lg'}`}>{getCurrentTime()}</div>
                            </div>
                        </div>
                        <div className={`col-span-4 ${previewMode ? 'border-2 border-blue-400 flex flex-col' : 'border-4 border-blue-500'}`}>
                            <div className={`bg-blue-500 text-white text-center font-bold leading-tight print:bg-blue-500 ${previewMode ? 'py-0 text-[10px]' : 'py-2'}`}>Hora Salida:</div>
                            <div className={previewMode ? 'bg-white flex flex-row items-center justify-center space-x-2 py-2 flex-1' : 'bg-white p-2'}>
                                <div className={`flex justify-center ${previewMode ? '' : 'mb-2'}`}>
                                    <span className={`bg-blue-100 rounded font-bold text-blue-600 ${previewMode ? 'px-1 py-0.5 text-[10px]' : 'px-3 py-1'}`}>{getDepartureTimeAmPm()}</span>
                                </div>
                                <div className={`text-center font-bold text-red-600 ${previewMode ? 'text-sm' : 'text-lg'}`}>{getDepartureTime()}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className={`bg-gradient-to-r from-cyan-400 to-blue-500 text-white flex flex-col print:bg-blue-500 print:!bg-none ${previewMode ? 'px-2 py-1 border-t-2 border-blue-500 pb-2' : 'px-4 py-3 border-t-4 border-blue-600'}`}>
                <div className={previewMode ? 'grid grid-cols-12 gap-1 items-stretch' : 'grid grid-cols-12 gap-4'}>
                    <div className="col-span-4 flex items-center justify-center">
                        <div className="text-center">
                            <p className={`font-bold mb-0 leading-tight uppercase tracking-widest text-[#FFDF00] ${previewMode ? 'text-[9px]' : 'text-lg'}`}>
                                NO SE ACEPTAN<br />DEVOLUCIONES
                            </p>
                            <p className={`italic opacity-90 tracking-wide mt-1 text-white ${previewMode ? 'text-[7px]' : 'text-sm mt-2'}`}>
                                ¡Gracias por su preferencia!
                            </p>
                        </div>
                    </div>
                    <div className="col-span-8 flex flex-col">
                        <div className={`bg-blue-600/50 rounded flex-1 flex flex-col justify-center ${previewMode ? 'px-2 py-1' : 'px-3 py-2'}`}>
                            <h4 className={`text-center font-bold ${previewMode ? 'text-[8px] mb-1' : 'text-sm mb-2'}`}>
                                HORARIOS DE SALIDA STZ - COMARAPA
                            </h4>
                            <div className={`leading-tight ${previewMode ? 'text-[6.5px] space-y-0.5' : 'text-xs space-y-1'}`}>
                                <div className="flex justify-between"><span className="font-bold opacity-80">L-J:</span> 10:30, 14:00, 18:30, 20:30</div>
                                <div className="flex justify-between"><span className="font-bold text-yellow-300">V-S-D:</span> 10:30, 14:00, 18:30, 20:30, 22:00</div>
                                <h4 className={`text-center font-bold border-t border-white/20 pt-1 mt-1 ${previewMode ? 'text-[8px] pb-0.5' : 'text-sm mt-2'}`}>
                                    HORARIOS COMARAPA - STZ
                                </h4>
                                <div className="flex justify-between"><span className="font-bold opacity-80">L-S:</span> 08:00, 14:00, 20:30, 23:30</div>
                                <div className="flex justify-between"><span className="font-bold text-yellow-300">DOM:</span> 08:30, 12:00, 14:00, 20:30, 23:30</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
